- name: Angular Deploy gh-pages Actions
  # You may pin to the exact commit or the version.
  # uses: AhsanAyaz/angular-deploy-gh-pages-actions@0e4f1a953d00116ca38fbf1bcdb37f91923015ef
  uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
  with:
    # Github access token token used to deploy on gh_pages. You can find it on Github.
    github_access_token: ${{ secrets.GITHUB_TOKEN }}
    # The directory of the angular project, in which all the commands will run
    angular_project_dir: /app/src # optional, default is ./
    # Build configuration for the angular app
    #build_configuration: # optional, default is production
    # base href for the app
    #base_href: # optional, default is /
    # branch on which the angular build will be deployed
    #deploy_branch: # optional, default is gh-pages
    # The folder in which `ng build` provides its output. This is the folder which will be deployed to the `deploy_branch`.
    #angular_dist_build_folder: # optional, default is dist
    # If the action should run 'ng lint'
    #run_lint: # optional
    # Will not fail the step if anything fails
    #skip_failure: # optional
